### PR TITLE
Rebase kube int

### PR DESCRIPTION
**Pull request by deads2k**
@kargakis This continues the previous pull and adds commits for integration tests.

I'm still chasing failures 
```

--- FAIL: TestBuildDeleteController-4 (5.74s)
	buildcontroller_test.go:568: expected watch event type DELETED, got MODIFIED


TestDNS


```

but its closer than it was.

### CODE REVIEW

**Comment by deads2k** [comment]
e2e is still failing
```
I0924 18:16:58.432472       1 sti.go:102] Starting S2I build from test/ruby-sample-build-1 BuildConfig ...
I0924 18:16:58.432489       1 sti.go:123] Preparing to build 172.30.208.7:5000/test/origin-ruby-sample:latest
I0924 18:16:58.433044       1 clone.go:28] Cloning into /tmp/sti978314926/upload/src
I0924 18:17:31.562943       1 clone.go:30] Git clone failed: exit status 128
I0924 18:17:31.562987       1 cleanup.go:23] Removing temporary directory /tmp/sti978314926
I0924 18:17:31.562994       1 fs.go:99] Removing directory '/tmp/sti978314926'
F0924 18:17:31.563175       1 builder.go:47] Build error: exit status 128
```

**Comment by deads2k** [comment]
@gabemontero can you look at the TestBuildDeleteController in this branch to see how to make the watch less fragile?

**Comment by pweil-** [comment]
@gabemontero - I took a pass at this in https://github.com/deads2k/origin/pull/14

**Comment by gabemontero** [comment]
don't have any insight beyond what already exists in the reference PRs: the most likely cause of the git clone failure is some form of IP level hiccup as previously surmised; retries or DNS manipulations are the initial steps that come to mind.

@bparees @csrwng @mfojtik - hopefully one of you can provide more helpful insight

**Pull request closed without merging**
