### PR TITLE
Kube rebase

### PR DESCRIPTION
**Pull request by deads2k**
@kargakis fixes --api-version for test-cmd

### CODE REVIEW

**Comment by deads2k** [comment]
@kargakis I'll rebase on top

**Comment by deads2k** [comment]
@kargakis you should be able to merge and then remove the "update deep-copy" commit.

**Comment by deads2k** [comment]
@kargakis @pweil- these changes give a clean test-cmd run

**Comment by kargakis** [comment]
Thanks, cherry-picked https://github.com/deads2k/origin/commit/6264ef3c2127a068bc969ee0fa78bd5e7cd396b3 and https://github.com/deads2k/origin/commit/166f4f9bd5de4c5cb094960046f832ff74d7e842

**Pull request closed without merging**
